// <auto-generated />
using DessertAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DessertAPI.Migrations
{
    [DbContext(typeof(DessertDbContext))]
    [Migration("20240904063428_DessertCreate")]
    partial class DessertCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DessertAPI.Models.Dessert", b =>
                {
                    b.Property<int>("DessertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DessertID"));

                    b.Property<string>("DessertName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DessertID");

                    b.ToTable("desserts");
                });

            modelBuilder.Entity("DessertAPI.Models.DessertFlavour", b =>
                {
                    b.Property<int>("DessertId")
                        .HasColumnType("int");

                    b.Property<int>("FlavourId")
                        .HasColumnType("int");

                    b.HasKey("DessertId", "FlavourId");

                    b.HasIndex("FlavourId");

                    b.ToTable("dessertFlavours");
                });

            modelBuilder.Entity("DessertAPI.Models.Flavour", b =>
                {
                    b.Property<int>("FlavourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlavourId"));

                    b.Property<string>("FlavourName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlavourId");

                    b.ToTable("flavours");
                });

            modelBuilder.Entity("DessertAPI.Models.DessertFlavour", b =>
                {
                    b.HasOne("DessertAPI.Models.Dessert", "dessert")
                        .WithMany("DessertFlavours")
                        .HasForeignKey("DessertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertAPI.Models.Flavour", "flavour")
                        .WithMany("DessertFlavours")
                        .HasForeignKey("FlavourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dessert");

                    b.Navigation("flavour");
                });

            modelBuilder.Entity("DessertAPI.Models.Dessert", b =>
                {
                    b.Navigation("DessertFlavours");
                });

            modelBuilder.Entity("DessertAPI.Models.Flavour", b =>
                {
                    b.Navigation("DessertFlavours");
                });
#pragma warning restore 612, 618
        }
    }
}
